// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: protos/ops/ops.proto

package opspbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	opspb "goakt-actors-cluster/internal/opspb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OpsServiceName is the fully-qualified name of the OpsService service.
	OpsServiceName = "opspb.OpsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OpsServiceGetClusterNodesProcedure is the fully-qualified name of the OpsService's
	// GetClusterNodes RPC.
	OpsServiceGetClusterNodesProcedure = "/opspb.OpsService/GetClusterNodes"
	// OpsServiceGetNodeDetailsProcedure is the fully-qualified name of the OpsService's GetNodeDetails
	// RPC.
	OpsServiceGetNodeDetailsProcedure = "/opspb.OpsService/GetNodeDetails"
	// OpsServiceHealthCheckProcedure is the fully-qualified name of the OpsService's HealthCheck RPC.
	OpsServiceHealthCheckProcedure = "/opspb.OpsService/HealthCheck"
	// OpsServiceGetClusterStatsProcedure is the fully-qualified name of the OpsService's
	// GetClusterStats RPC.
	OpsServiceGetClusterStatsProcedure = "/opspb.OpsService/GetClusterStats"
)

// OpsServiceClient is a client for the opspb.OpsService service.
type OpsServiceClient interface {
	// GetClusterNodes returns the list of all nodes in the cluster
	GetClusterNodes(context.Context, *connect.Request[opspb.GetClusterNodesRequest]) (*connect.Response[opspb.GetClusterNodesResponse], error)
	// GetNodeDetails returns detailed information about a specific node
	GetNodeDetails(context.Context, *connect.Request[opspb.GetNodeDetailsRequest]) (*connect.Response[opspb.GetNodeDetailsResponse], error)
	// HealthCheck performs a health check on the current node
	HealthCheck(context.Context, *connect.Request[opspb.HealthCheckRequest]) (*connect.Response[opspb.HealthCheckResponse], error)
	// GetClusterStats returns cluster-wide statistics
	GetClusterStats(context.Context, *connect.Request[opspb.ClusterStatsRequest]) (*connect.Response[opspb.ClusterStatsResponse], error)
}

// NewOpsServiceClient constructs a client for the opspb.OpsService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOpsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OpsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	opsServiceMethods := opspb.File_protos_ops_ops_proto.Services().ByName("OpsService").Methods()
	return &opsServiceClient{
		getClusterNodes: connect.NewClient[opspb.GetClusterNodesRequest, opspb.GetClusterNodesResponse](
			httpClient,
			baseURL+OpsServiceGetClusterNodesProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetClusterNodes")),
			connect.WithClientOptions(opts...),
		),
		getNodeDetails: connect.NewClient[opspb.GetNodeDetailsRequest, opspb.GetNodeDetailsResponse](
			httpClient,
			baseURL+OpsServiceGetNodeDetailsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetNodeDetails")),
			connect.WithClientOptions(opts...),
		),
		healthCheck: connect.NewClient[opspb.HealthCheckRequest, opspb.HealthCheckResponse](
			httpClient,
			baseURL+OpsServiceHealthCheckProcedure,
			connect.WithSchema(opsServiceMethods.ByName("HealthCheck")),
			connect.WithClientOptions(opts...),
		),
		getClusterStats: connect.NewClient[opspb.ClusterStatsRequest, opspb.ClusterStatsResponse](
			httpClient,
			baseURL+OpsServiceGetClusterStatsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetClusterStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// opsServiceClient implements OpsServiceClient.
type opsServiceClient struct {
	getClusterNodes *connect.Client[opspb.GetClusterNodesRequest, opspb.GetClusterNodesResponse]
	getNodeDetails  *connect.Client[opspb.GetNodeDetailsRequest, opspb.GetNodeDetailsResponse]
	healthCheck     *connect.Client[opspb.HealthCheckRequest, opspb.HealthCheckResponse]
	getClusterStats *connect.Client[opspb.ClusterStatsRequest, opspb.ClusterStatsResponse]
}

// GetClusterNodes calls opspb.OpsService.GetClusterNodes.
func (c *opsServiceClient) GetClusterNodes(ctx context.Context, req *connect.Request[opspb.GetClusterNodesRequest]) (*connect.Response[opspb.GetClusterNodesResponse], error) {
	return c.getClusterNodes.CallUnary(ctx, req)
}

// GetNodeDetails calls opspb.OpsService.GetNodeDetails.
func (c *opsServiceClient) GetNodeDetails(ctx context.Context, req *connect.Request[opspb.GetNodeDetailsRequest]) (*connect.Response[opspb.GetNodeDetailsResponse], error) {
	return c.getNodeDetails.CallUnary(ctx, req)
}

// HealthCheck calls opspb.OpsService.HealthCheck.
func (c *opsServiceClient) HealthCheck(ctx context.Context, req *connect.Request[opspb.HealthCheckRequest]) (*connect.Response[opspb.HealthCheckResponse], error) {
	return c.healthCheck.CallUnary(ctx, req)
}

// GetClusterStats calls opspb.OpsService.GetClusterStats.
func (c *opsServiceClient) GetClusterStats(ctx context.Context, req *connect.Request[opspb.ClusterStatsRequest]) (*connect.Response[opspb.ClusterStatsResponse], error) {
	return c.getClusterStats.CallUnary(ctx, req)
}

// OpsServiceHandler is an implementation of the opspb.OpsService service.
type OpsServiceHandler interface {
	// GetClusterNodes returns the list of all nodes in the cluster
	GetClusterNodes(context.Context, *connect.Request[opspb.GetClusterNodesRequest]) (*connect.Response[opspb.GetClusterNodesResponse], error)
	// GetNodeDetails returns detailed information about a specific node
	GetNodeDetails(context.Context, *connect.Request[opspb.GetNodeDetailsRequest]) (*connect.Response[opspb.GetNodeDetailsResponse], error)
	// HealthCheck performs a health check on the current node
	HealthCheck(context.Context, *connect.Request[opspb.HealthCheckRequest]) (*connect.Response[opspb.HealthCheckResponse], error)
	// GetClusterStats returns cluster-wide statistics
	GetClusterStats(context.Context, *connect.Request[opspb.ClusterStatsRequest]) (*connect.Response[opspb.ClusterStatsResponse], error)
}

// NewOpsServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOpsServiceHandler(svc OpsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	opsServiceMethods := opspb.File_protos_ops_ops_proto.Services().ByName("OpsService").Methods()
	opsServiceGetClusterNodesHandler := connect.NewUnaryHandler(
		OpsServiceGetClusterNodesProcedure,
		svc.GetClusterNodes,
		connect.WithSchema(opsServiceMethods.ByName("GetClusterNodes")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetNodeDetailsHandler := connect.NewUnaryHandler(
		OpsServiceGetNodeDetailsProcedure,
		svc.GetNodeDetails,
		connect.WithSchema(opsServiceMethods.ByName("GetNodeDetails")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceHealthCheckHandler := connect.NewUnaryHandler(
		OpsServiceHealthCheckProcedure,
		svc.HealthCheck,
		connect.WithSchema(opsServiceMethods.ByName("HealthCheck")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetClusterStatsHandler := connect.NewUnaryHandler(
		OpsServiceGetClusterStatsProcedure,
		svc.GetClusterStats,
		connect.WithSchema(opsServiceMethods.ByName("GetClusterStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/opspb.OpsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OpsServiceGetClusterNodesProcedure:
			opsServiceGetClusterNodesHandler.ServeHTTP(w, r)
		case OpsServiceGetNodeDetailsProcedure:
			opsServiceGetNodeDetailsHandler.ServeHTTP(w, r)
		case OpsServiceHealthCheckProcedure:
			opsServiceHealthCheckHandler.ServeHTTP(w, r)
		case OpsServiceGetClusterStatsProcedure:
			opsServiceGetClusterStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOpsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOpsServiceHandler struct{}

func (UnimplementedOpsServiceHandler) GetClusterNodes(context.Context, *connect.Request[opspb.GetClusterNodesRequest]) (*connect.Response[opspb.GetClusterNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("opspb.OpsService.GetClusterNodes is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetNodeDetails(context.Context, *connect.Request[opspb.GetNodeDetailsRequest]) (*connect.Response[opspb.GetNodeDetailsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("opspb.OpsService.GetNodeDetails is not implemented"))
}

func (UnimplementedOpsServiceHandler) HealthCheck(context.Context, *connect.Request[opspb.HealthCheckRequest]) (*connect.Response[opspb.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("opspb.OpsService.HealthCheck is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetClusterStats(context.Context, *connect.Request[opspb.ClusterStatsRequest]) (*connect.Response[opspb.ClusterStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("opspb.OpsService.GetClusterStats is not implemented"))
}
